[ServerSettings]
NPCMindReadingMode=0
; 2=Full, 1=Partial, 0=None
MaxNudity=0
ServerCommunity=0
ConfigVersion=13
BlueprintConfigVersion=25
BuildingPVPWhitelist=("80901","80111","80112","80915","80912")
PlayerKnockbackMultiplier=1.000000
NPCKnockbackMultiplier=1.000000
StructureDamageMultiplier=1.000000
StructureHealthMultiplier=1.000000
NPCRespawnMultiplier=1.000000
NPCHealthMultiplier=1.000000
PlayerDamageMultiplier=1.000000
PlayerDamageTakenMultiplier=1.000000
MinionDamageMultiplier=1.000000
MinionDamageTakenMultiplier=1.000000
NPCDamageMultiplier=1.000000
NPCDamageTakenMultiplier=1.000000
PlayerEncumbranceMultiplier=1.000000
PlayerEncumbrancePenaltyMultiplier=1.000000
PlayerMovementSpeedScale=1.000000
PlayerStaminaCostSprintMultiplier=1.000000
PlayerSprintSpeedScale=1.000000
PlayerStaminaCostMultiplier=1.000000
PlayerHealthRegenSpeedScale=1.000000
PlayerXPRateMultiplier=1.000000
PlayerXPKillMultiplier=1.000000
PlayerXPHarvestMultiplier=1.000000
PlayerXPCraftMultiplier=1.000000
PlayerXPTimeMultiplier=1.000000
DogsOfTheDesertSpawnWithDogs=False
CrossDesertOnce=True
ThrallExclusionRadius=100.000000
MaxAggroRange=9000.000000
FriendlyFireDamageMultiplier=0.250000
CampsIgnoreLandclaim=True
AvatarDomeDurationMultiplier=1.000000
AvatarDomeDamageMultiplier=1.000000
NPCMaxSpawnCapMultiplier=1.000000
PvPMountEnduranceDamageMultiplier=1.000000
; 3=Asia, 2=Americas, 1/0=Europe
serverRegion=0
AmbientLifeEnabled=True
PVPEnabled=False
RestrictPVPTime=False
RestrictPVPBuildingDamageTime=False
PVPTimeMondayStart=0
PVPTimeTuesdayStart=0
PVPTimeWednesdayStart=0
PVPTimeThursdayStart=0
PVPTimeFridayStart=0
PVPTimeSaturdayStart=0
PVPTimeSundayStart=0
PVPTimeMondayEnd=0
PVPTimeTuesdayEnd=0
PVPTimeWednesdayEnd=0
PVPTimeThursdayEnd=0
PVPTimeFridayEnd=0
PVPTimeSaturdayEnd=0
PVPTimeSundayEnd=0
PVPEnabledMonday=False
PVPEnabledTuesday=False
PVPEnabledWednesday=False
PVPEnabledThursday=False
PVPEnabledFriday=False
PVPEnabledSaturday=False
PVPEnabledSunday=False
PVPBuildingDamageTimeMondayStart=0
PVPBuildingDamageTimeTuesdayStart=0
PVPBuildingDamageTimeWednesdayStart=0
PVPBuildingDamageTimeThursdayStart=0
PVPBuildingDamageTimeFridayStart=0
PVPBuildingDamageTimeSaturdayStart=0
PVPBuildingDamageTimeSundayStart=0
PVPBuildingDamageTimeMondayEnd=0
PVPBuildingDamageTimeTuesdayEnd=0
PVPBuildingDamageTimeWednesdayEnd=0
PVPBuildingDamageTimeThursdayEnd=0
PVPBuildingDamageTimeFridayEnd=0
PVPBuildingDamageTimeSaturdayEnd=0
PVPBuildingDamageTimeSundayEnd=0
PVPBuildingDamageEnabledMonday=False
PVPBuildingDamageEnabledTuesday=False
PVPBuildingDamageEnabledWednesday=False
PVPBuildingDamageEnabledThursday=False
PVPBuildingDamageEnabledFriday=False
PVPBuildingDamageEnabledSaturday=False
PVPBuildingDamageEnabledSunday=False
DisableBuildingDuringTimeRestrictedPVP=False
CombatModeModifier=0
ContainersIgnoreOwnership=True
LandClaimRadiusMultiplier=1.000000
DisableLandclaimNotifications=True
BuildingPreloadRadius=80.000000
CanDamagePlayerOwnedStructures=False
DynamicBuildingDamage=False
DynamicBuildingDamagePeriod=1800
CreativeModeServer=0
ServerPassword=
ServerMessageOfTheDay=
KickAFKPercentage=80
KickAFKTime=2700
OfflinePlayersUnconsciousBodiesHours=168
ShowOnlinePlayers=0
CorpsesPerPlayer=10
PlayerCorpseLifeTime=1800.000000
NPCCorpseLifeTime=600.000000
ItemRepairMinimumDurability=0.100000
ItemRepairDurabilityLossByRepairkitTier=(0.200000,0.200000,0.150000,0.100000,0.050000,0.025000)
ItemRepairDurabilityLossPenaltyChance=1.000000
ItemConvertionMultiplier=1.000000
ThrallConversionMultiplier=1.000000
FuelBurnTimeMultiplier=1.000000
CraftingCostMultiplier=1.000000
StaminaRegenerationTime=3.750000
StaminaExhaustionTime=3.750000
StaminaStaticRegenRateMultiplier=1.000000
StaminaMovingRegenRateMultiplier=1.000000
PlayerStaminaRegenSpeedScale=1.000000
StaminaOnConsumeRegenPause=1.300000
StaminaOnExhaustionRegenPause=2.750000
ThrallScoutingTimeMinutes=10.000000
ThrallMinDistanceAwayFromHome=5000.000000
ThrallTeleportingCooldown=10.000000
MinionPopulationBaseValue=50
MinionPopulationPerPlayer=5
MinionOverpopulationCleanup=60
MinionOverpopulationAllowed=10
EnableFollowerDbno=True
UseMinionPopulationLimit=False
EnableFollowerRescueOnLandClaimOnly=True
EnableFollowerRescueInBuildExclusionZone=False
FollowerRescueCooldown=3600
DamageCooldownBeforeRescue=600
ThrallCorruptionRemovalMultiplier=1.000000
PlayerCorruptionGainMultiplier=1.000000
PlayerCorruptionGainFromSorceryMultiplier=1.000000
AnimalPenCraftingTimeMultiplier=1.000000
FeedBoxRangeMultiplier=1.000000
BuildingDamageMultiplier=1.000000
PathFollowingSendsAngularVelocity=False
UnconsciousTimeSeconds=1800.000000
ConciousnessDamageMultiplier=1.000000
ThrallDamageToPlayersMultiplier=0.500000
ThrallDamageToNPCsMultiplier=0.500000
DisableBuildingAbandonment=True
MaxBuildingDecayTime=1296000.000000
MaxDecayTimeToAutoDemolish=604800.000000
ThrallDecayTime=1296000.000000
DisableThrallDecay=True
BuildingDecayTimePerScore=5400.000000
BuildingDecayTimeMultiplier=1.000000
DecayCleanupTimeMultiplier=2.000000
DecayBonusTimeRate=600.000000
DecayShowBuildingScore=False
EnableTargetLock=True
EnableFatalities=True
CachedLandClaimRadiusMultiplier=1.000000
ValidatePhysNavWalkWithRaycast=True
LocalNavMeshVisualizationFrequency=-1.000000
LocalLandClaimVisualizationFrequency=-1.000000
LocalLandClaimVisualizationRadius=3000
LocalLandClaimVisualizationChannel=0
UseLocalQuadraticAngularVelocityPrediction=False
LQAVPUseTime=0.150000
LQAVPFadeTime=0.100000
LQAVPMethod=2
NetworkSimulatedSmoothRotationTimeWithLQAVP=0.100000
EnableClanMarkers=True
ValidatePlayerStats=False
AllowedTimeUndermesh=-1.000000
AllowedDistanceUndermeshSquared=490000.000000
CapCharacterLayoutScalarParams=False
EventLogPvPCauserPrivacy=2
EventLogPvECauserPrivacy=1
serverVoiceChat=1
AvatarsDisabled=False
RestrictAvatarSummoningTime=False
AvatarSummoningTimeWeekdayStart=0
AvatarSummoningTimeWeekdayEnd=0
AvatarSummoningTimeWeekendStart=0
AvatarSummoningTimeWeekendEnd=0
AvatarLifetime=600.000000
AvatarSummonTime=60.000000
MaxDeathMapMarkers=3
; Disable for linux.
IsBattlEyeEnabled=False
; Disable for linux.
IsVACEnabled=True
CanImportDirectlyFromSameServer=False
ServerTransferServersWhitelist=
MaxAllowedPing=0
AllowFamilySharedAccount=True
RegionAllowAfrica=True
RegionAllowAsia=True
RegionAllowCentralEurope=True
RegionAllowEasternEurope=True
RegionAllowWesternEurope=True
RegionAllowNorthAmerica=True
RegionAllowOceania=True
RegionAllowSouthAmerica=True
RegionBlockList=
ServerModList=
BuildingPickupEnabled=True
PoiProtectionEnabled=False
EventSystemEnabled=True
StabilityLossMultiplier=1.000000
BuildingValidationEnabled=False
AllowBuildingAnywhere=False
HealthbarVisibilityDistance=15000.000000
ServerMergeOutgoingTime=0
ServerMergeDestination=
DisableChatFormatting=False
EnableLoginQueue=True
DisconnectionGraceTime=180
bCanBeDamaged=True
; All options below are not explicitly set in default installs.
PurgeNPCBuildingDamageMultiplier=(5.0, 5.0, 10.0, 15.0, 20.0, 25.0)
VocalVisibilityDurationInMinutes=5
EnableAutoFacingOnAttack=True
InitialPurgeDelay=15.000000
LogoutCharactersRemainInTheWorld=True
OverrideDecayMaxBuildingPieces=6
OverrideDecayTime=3600
AdminPassword=changeme
PlayerFoodMultiplier=1.000000
PlayerWaterMultiplier=1.000000
PlayerIdleThirstMultiplier=1.000000
PlayerActiveThirstMultiplier=1.000000
PlayerOfflineThirstMultiplier=0.000000
PlayerIdleHungerMultiplier=1.000000
PlayerActiveHungerMultiplier=1.000000
PlayerOfflineHungerMultiplier=0.000000
ShieldDurabilityMultiplier=1.000000
NoOwnership=False
BuildingRadialDestructionForceMultiplier=500.000000
DurabilityMultiplier=1.000000
DropEquipmentOnDeath=True
EverybodyCanLootCorpse=False
TetheringMinLimit=12000.0
TetheringMaxLimit=102000.0
CoopTetheringLimit=52000.0
TetheringRangeDelta=2000.0
DayCycleSpeedScale=1.000000
DayTimeSpeedScale=1.000000
NightTimeSpeedScale=1.000000
DawnDuskSpeedScale=1.000000
ClientCatchUpTime=10.000000
UseClientCatchUpTime=True
PlayerHealthMultiplier=1.000000
PlayerStaminaMultiplier=1.000000
StaminaCostMultiplier=1.000000
ItemSpoilRateScale=1.000000
HarvestAmountMultiplier=1.000000
ResourceRespawnSpeedMultiplier=1.000000
ChatHasGlobal=True
ChatLocalRadius=5000.000000
ChatMaxMessageLength=512
ChatFloodControlAheadCounter=10
EnableSandStorm=True
ClanMaxSize=30
IsLoadErrorsFatal=False
IPBlackList=("8.8.8.8","8.8.4.4")
PurgeLevel=6
PurgeDelay=5
RestrictPurgeTime=False
PurgeRestrictionWeekdayStart=1800
PurgeRestrictionWeekdayEnd=2200
PurgeRestrictionWeekendStart=1800
PurgeRestrictionWeekendEnd=2200
MinPurgeOnlinePlayers=0
ClanPurgeTrigger=42000
ClanScoreUpateFrequency=15
PurgeDuration=30
PurgePreparationTime=10
AllowBuilding=False
EnablePurge=True
PlayerBuildingDamageMultiplier=' = 0.01'
OverrideDecayTime=3600
EnableWhitelist=False
EnableBanCheck=True
; Isle of Siptah expanded options.
StormEnabled=True
ElderThingsEnabled=True
ElderThingsIdleLifespan=30.000000
SiegeElderThingsEnabled=False
StormCooldown=105.000000
StormAccumulationTime=1.000000
StormDuration=15.000000
StormDissipationTime=1.000000
StormEnduranceDrainMultiplier=0.000000
ElderThingSpawnRate=1.000000
StormTimeWeekdayStart='0000'
StormTimeWeekdayEnd=2359
StormTimeWeekendStart='0000'
StormTimeWeekendEnd=2359
StormMinimumOnlinePlayers=0
StormBuildingAllowed=True
StormMapBlocker=True
EnableBuildingDestructionCapsules=False
ServerTransferEnabled=False
; These are feature ID's to blacklist, format: ("ID", "ID", "ID")
FeatsBlacklist=''
CanDamagePlayerOwnedStructuresPeriod=120
ElderThingSiegeDamageMultiplier=1.000000
MinimumBuildingSizeToBeSieged=41
AmbientElderThingRespawnRate=1.000000
SiegeElderThingRespawnRate=1.000000
StormBuildingDamageRateMultiplier=1.000000
MaxAmbientElderThings=700
MaxSiegeElderThings=5
MaxAmbushElderThings=200
ElderThingSiegeBuildingSizeMultiplier=1.000000
StormBuildingDamageEnabled=False
SiegeElderThingMapMarkers=False
MinimumStormDamageBuildingPieces=0
StormBuildingDamageMultiplier=1.000000
VaultRefreshTime=10
VaultRefreshDeviation=2
SurgeDeviationMin=60
SurgeDeviationMax=60
SurgeSacrificeRequirementMultiplier=1.000000
SurgeDespawnTimer=90
AltarModuleActiveTimeMultiplier=1.000000
RandomSurgesCountMin=6
RandomSurgesCountMax=10
DecoupleSurgeFromStorm=False
DecoupledSurgeCooldown=5
