---
###############################################################################
# Config
###############################################################################
# Server will automatically populate any required .ini file if it does not
# exist on service start. Any pre-existing .ini file will not be touched and
# assumed correct.
#
# Only set configuration files if they are defined.
#
# Documentation for linux systemd services is very outdated. Checking service
# against documentation will not line up. Only check if there are new options.
#
# Filetree returns a dict (instead of a list of dict) for one element. Use
# query to guarantee a list result.
#
# Reference:
# * https://conanexiles.fandom.com/wiki/Dedicated_Server_Setup:_Linux_and_Wine

- name: 'Config | filetree | deploy managed files'
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ conan_exiles__cfg._ini_dir ~ "/" ~ item.path }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0644'
  loop: '{{ query("community.general.filetree", conan_exiles__cfg._cfg_dir) }}'
  loop_control:
    label: '{{ item.path }}'
  when: item.state == 'file'
  register: conan_exiles__local

- name: 'Config | filesystem | query remote files'
  ansible.builtin.find:
    paths: '{{ conan_exiles__cfg._ini_dir }}'
    file_type: 'file'
    recurse: true
  register: conan_exiles__remote

- name: 'Config | filesystem | remove unmanaged files'
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: 'absent'
  loop: '{{ conan_exiles__remote.files }}'
  loop_control:
    label: '{{ item.path }}'
  when: >
    item.path not in conan_exiles__local.results | map(attribute='dest') | list

- name: '{{ "Config | filesystem | disable " ~ conan_exiles__cfg._mod_file }}'
  when: conan_exiles__cfg._mod_list | length == 0
  ansible.builtin.file:
    dest: '{{ conan_exiles__cfg.mod_list }}'
    state: 'absent'
