---
###############################################################################
# Install
###############################################################################
# Create service and backup directories, configuration files.

- name: 'Install | steamcmd'
  ansible.builtin.import_role:
    name: 'r_pufky.game.steam'
  vars:
    steam_flg_wine: true
    steam_flg_container: '{{ conan_exiles_flg_container }}'
    steam_flg_cdn: '{{ conan_exiles_flg_cdn }}'
    steam_flg_update: false
    steam_srv_token: '{{ conan_exiles__srv._token }}'

- name: 'Install | filesystem | find current installation'
  ansible.builtin.stat:
    path: '{{ conan_exiles___app._bin }}'
  register: conan_exiles__installed

- name: 'Install | fact | set install state'
  ansible.builtin.set_fact:
    conan_exiles__cfg: "{{ conan_exiles__cfg | r_pufky.data.v3(

        _is_installed=conan_exiles__installed.stat.exists,
      ) }}"

- name: 'Install | filesystem | set server directories'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ steam__ctx._uid }}'
    group: '{{ steam__ctx._gid }}'
    mode: '0775'  # Game enforced.
    state: 'directory'
  loop:
    - '{{ conan_exiles___app._root_d }}'
    - '{{ conan_exiles___app._ini_d }}'
    - '{{ conan_exiles___app._mod_d }}'

- name: '{{ "Install | filesystem | set " ~ conan_exiles__cfg._backup_d }}'
  when: conan_exiles_flg_backup
  block:
    - name: '{{ "Install | filesystem | set " ~ conan_exiles__cfg._backup_d }}'
      ansible.builtin.file:
        path: '{{ conan_exiles__cfg._backup_d }}'
        owner: '{{ steam__ctx._uid }}'
        group: '{{ steam__ctx._gid }}'
        mode: '0755'
        state: 'directory'
  rescue:
    - name:
        '{{ "Install ⛑ | filesystem | set " ~ conan_exiles__cfg._backup_d }}'
      ansible.builtin.file:
        path: '{{ conan_exiles__cfg._backup_d }}'
        owner: '{{ steam__ctx._uid }}'
        group: '{{ steam__ctx._gid }}'
        mode: '0755'
        state: 'directory'
      become: true
      become_user: '{{ steam__ctx._user }}'

- name: 'Install | systemd | set conan_exiles.service'
  ansible.builtin.template:
    src: 'systemd/conan_exiles.service.j2'
    dest: '/etc/systemd/system/conan_exiles.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
