---
# yamllint disable rule:line-length
###############################################################################
# Install
###############################################################################
# Create service and backup directories, configuration files, and copy mods if
# enabled.
#
# Reference:
# * https://conanexiles.fandom.com/wiki/Dedicated_Server_Setup:_Linux_and_Wine#General_notes
# * https://forums.funcom.com/t/hosting-a-dedicated-server-for-isle-of-siptah/136857
# * https://www.conanexiles.com/dedicated-servers/
# yamllint enable rule:line-length

- name: 'Install | steamcmd'
  ansible.builtin.import_role:
    name: 'r_pufky.game.steam'
  vars:
    steam_flg_wine: true
    steam_flg_update: false
    steam_srv_token: '{{ conan_exiles__srv._token }}'

- name: 'Install | filesystem | find current installation'
  ansible.builtin.stat:
    path: '{{ conan_exiles__cfg._app }}'
  register: conan_exiles__installed

- name: 'Install | fact | set install state'
  ansible.builtin.set_fact:
    conan_exiles__cfg: "{{ conan_exiles__cfg | r_pufky.data.v3(

        _is_installed=conan_exiles__installed.stat.exists,
      ) }}"

- name: 'Install | filesystem | set server directories'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ steam__ctx._uid }}'
    group: '{{ steam__ctx._gid }}'
    mode: '0775'  # Game enforced.
    state: 'directory'
  loop:
    - '{{ conan_exiles__cfg._root_dir }}'
    - '{{ conan_exiles__cfg._ini_dir }}'
    - '{{ conan_exiles__cfg._mod_dir }}'

- name: '{{ "Install | filesystem | set " ~ conan_exiles__cfg._backup_dir }}'
  when: conan_exiles_flg_backup
  ansible.builtin.file:
    path: '{{ conan_exiles__cfg._backup_dir }}'
    owner: '{{ steam__ctx._uid }}'
    group: '{{ steam__ctx._gid }}'
    mode: '0755'
    state: 'directory'

- name: 'Install | systemd | set conan_exiles.service'
  ansible.builtin.template:
    src: 'systemd/conan_exiles.service.j2'
    dest: '/etc/systemd/system/conan_exiles.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
