---
###############################################################################
# Mod Configuration
###############################################################################
# Mods are automatically downloaded and installed. Only listed mods are
# enabled.
#
# * Mod list generated in specified list order.
# * '*' is automatically pre-pended to the mod name for loading.

- name: '{{ "Mod | steamcmd | update " ~ item }}'
  ansible.builtin.shell: '{{
      conan_exiles___app._steamcmd ~
      "+workshop_download_item " ~ conan_exiles___release._store_id ~ " " ~
      item ~ " +quit"
    }}'
  args:
    executable: '/bin/bash'
    chdir: '{{ steam__ctx._home }}'
  changed_when: false
  become: true
  become_user: '{{ steam__ctx._user }}'

- name: '{{ "Mod | filesystem | parse " ~ item }}'
  ansible.builtin.find:
    path: '{{ conan_exiles___app._workshop_d ~ "/" ~ item }}'
    patterns: '*.pak'
    file_type: 'file'
    limit: 1
  register: conan_exiles__mod

- name: '{{
      "Mod | filesystem | install " ~
      conan_exiles__mod.files[0].path | basename
    }}'
  ansible.builtin.copy:
    remote_src: true
    src: '{{ conan_exiles__mod.files[0].path }}'
    dest: '{{ conan_exiles___app._mod_d ~ "/" }}'
    owner: '{{ steam__ctx._uid }}'
    group: '{{ steam__ctx._gid }}'
    mode: '0644'
    directory_mode: '0775'
    force: true

- name: '{{ "Mod | filsystem | update " ~ conan_exiles___app._mod_list }}'
  ansible.builtin.lineinfile:
    path: '{{ conan_exiles___app._mod_list }}'
    line: '{{ "*" ~ conan_exiles__mod.files[0].path | basename }}'
    insertafter: 'EOF'
    owner: '{{ steam__ctx._uid }}'
    group: '{{ steam__ctx._gid }}'
    mode: '0644'
    create: true
