---
###############################################################################
# Pre Execution Tasks
###############################################################################
# Only use data annotations in role after merging role, defaults, runtime data.
# Service may not exist if first install.

- name:
    'Prep | fact | force conan_exiles_flg_container=true (deb_flg_container)'
  when: deb_flg_container | default(false)
  ansible.builtin.set_fact:
    conan_exiles_flg_container: true

- name: 'Prep | fact | record start time'
  ansible.builtin.set_fact:
    conan_exiles__srv: "{{ conan_exiles___release | r_pufky.data.v3(

        _start=now(utc=True, fmt='%Y-%m-%dT%H%M%S'),
        _token=conan_exiles_srv_token,
        _update_opts=conan_exiles_srv_update_opts | join(' '),
        _launch_opts=(
          conan_exiles_srv_launch_opts | map('regex_replace', '^', '-') |
          join(' ')
        ),
      ) }}"
    conan_exiles__cfg: "{{ {} | r_pufky.data.v3(

        _cfg_d=conan_exiles_cfg_d | regex_replace('\\/$', ''),
        _mods=conan_exiles_cfg_mods,
        _backup_mods=conan_exiles_cfg_backup_mods,
        _backup_d=conan_exiles_cfg_backup_d | regex_replace('\\/$', ''),
        _backup_schedule=conan_exiles_cfg_backup_schedule,
      ) }}"

- name: 'Prep | assert | config enabled and source defined'
  when: conan_exiles_flg_config
  ansible.builtin.assert:
    quiet: true
    that:
      - conan_exiles__cfg._cfg_d | length > 0
    fail_msg: |

      ✘ Config source not set.
      Config source enabled but no config source defined.

      conan_exiles_flg_config: {{ conan_exiles_flg_config }}
      conan_exiles_cfg_file: {{ conan_exiles__cfg._cfg_d }}

- name: 'Prep | systemd | stop conan_exiles.service'
  ansible.builtin.systemd:
    name: 'conan_exiles.service'
    state: 'stopped'
  failed_when: false
