---
# yamllint disable rule:line-length
###############################################################################
# Install
###############################################################################
# Updating will also install if not pre-existing, and copy mods if enabled.
#
# Reference:
# * https://conanexiles.fandom.com/wiki/Dedicated_Server_Setup:_Linux_and_Wine#General_notes
# * https://forums.funcom.com/t/hosting-a-dedicated-server-for-isle-of-siptah/136857
# * https://www.conanexiles.com/dedicated-servers/
# yamllint enable rule:line-length

- name: 'Update | steamcmd | 🗘 updating server (4.5GB, ~3 minutes) 🗘'
  ansible.builtin.debug:
    msg: |

      🗘 Updating ~4.5GB (~3 minutes @ 200Mbps). 🗘

- name: '{{ "Update | steamcmd | update " ~ conan_exiles___release._app_id }}'
  ansible.builtin.shell: '{{
      conan_exiles___app._steamcmd ~
      "+app_update " ~ conan_exiles___release._app_id ~ " " ~
      conan_exiles__srv._update_opts ~ " " ~
      "+quit"
    }}'
  args:
    executable: '/bin/bash'
    chdir: '{{ steam__ctx._home }}'
  changed_when: false
  become: true
  become_user: '{{ steam__ctx._user }}'

- name:
    '{{ "Update | filesystem | remove " ~ conan_exiles___app._mod_list }}'
  ansible.builtin.file:
    path: '{{ conan_exiles___app._mod_list }}'
    state: 'absent'

- name: 'Update | steamcmd | 🗘 install mods (~2 minutes) 🗘'
  when: conan_exiles__cfg._mods | length > 0
  ansible.builtin.debug:
    msg: |

      🗘 Updating mods (~2 minutes). 🗘

      {{ conan_exiles__cfg._mods | length }} to synchronize.

- name: 'Update | mod'
  when: conan_exiles__cfg._mods | length > 0
  ansible.builtin.include_tasks: 'mod.yml'
  loop: '{{ conan_exiles__cfg._mods }}'
