---
# yamllint disable rule:line-length
###############################################################################
# Default
###############################################################################
# Default values result in running Conan Exiles server.
#
# Requirements:
# * steam role must exist adjacent to conan_exiles.
# * Extremely heavy test setup (~8GB). Use --destroy=never.
#
# Tests:
# * Mods are installed correctly.
# * Engine.ini set.
# * Game.ini set.
# * ServerSettings.ini set.
# * Conan Exiles server is running.
# * Backup jobs are created.

dependency:
  name: 'galaxy'
driver:
  name: 'vagrant'
  provider:
    name: 'libvirt'
    type: 'libvirt'
provisioner:
  name: 'ansible'
  connection_options:
    ansible_ssh_user: 'vagrant'
    ansible_become: true
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
  inventory:
    group_vars:
      all:
        url_inject_enable: true
        conan_exiles_flg_update: false
        conan_exiles_flg_config: true
        conan_exiles_flg_backup: true
        conan_exiles_cfg_dir: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/files/siptah"
          }}'
        conan_exiles_cfg_mod_list:
          - 2723987721
platforms:
  - name: 'conan-exiles-default'
    box: 'debian/trixie64'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: 'private_network'
        auto_config: true
        type: 'dhcp'
    instance_raw_config_args:
      - 'vm.network "forwarded_port", guest: 7777, host: 7777, protocol: "udp"'
      - 'vm.network "forwarded_port", guest: 7777, host: 7777, protocol: "tcp"'
      - 'vm.network "forwarded_port", guest: 7778, host: 7778, protocol: "udp"'
      - 'vm.network "forwarded_port", guest: 27015, host: 27015, protocol: "udp"'
      - 'vm.network "forwarded_port", guest: 25575, host: 25575, protocol: "tcp"'
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
